depth_anything:
  ros__parameters:
    # Model configuration
    log_level: 'debug'
    model_file : ''
    encoder: vits
    device : 'cpu'
    # ROS topic configuration
    image_topic: /camera/image_raw
    depth_image_topic : /depth
