depth_anything:
  ros__parameters:
    # Model configuration
    log_level: 'debug'
    model_file : ''
    encoder: vits
    device : 'cpu'
    # ROS topic configuration
    image_topic: /depth_camera/image_raw_throttle
    depth_image_topic : /depth_camera/depth/image_raw
    camera_info_pub_topic: /depth_camera/depth/camera_info
    camera_info_sub_topic: /depth_camera/camera_info
    max_depth: 0.5
